### ISSUE TITLE
Access rules in ForgotPasswordHelper should be accessible to Guest_ResetPassword role

### ISSUE THREAD

**Issue by lordlothar99** [jaspervanderhoek/Forgot-Password#4]
In 3.5.0 : Acces rules defined in ForgotPasswordHelper give authorization to Guest_Signup role, but not to Guest_ResetPassword --> it's imposssible to set the email address in Step1_ForgotPassword page

**Comment by jaspervanderhoek** [comment]
Fixed in 3.5.1
